// =====================================================
// PDF EXPORT
// ParaCycling Federation Management System
// =====================================================

const {
  jsPDF
} = window.jspdf

const autoTable =
  window.jspdf
    ?.autoTable

import {
  EXPORT_CONFIG,
  buildFileName
}
from './exportConstants.js'

// =====================================================
// DOCUMENT
// =====================================================

export function createPdf({

  orientation =
    'landscape',

  unit =
    'mm',

  format =
    'a4'

} = {}) {

  return new jsPDF({

    orientation,
    unit,
    format

  })

}

// =====================================================
// HEADER
// =====================================================

export function addReportHeader({

  pdf,

  reportTitle,

  reportSubtitle = ''

}) {

  pdf.setFontSize(18)

  pdf.text(

    EXPORT_CONFIG.organization,

    14,

    15

  )

  pdf.setFontSize(14)

  pdf.text(
    reportTitle,
    14,
    24
  )

  if (
    reportSubtitle
  ) {

    pdf.setFontSize(10)

    pdf.text(
      reportSubtitle,
      14,
      30
    )

  }

}

// =====================================================
// GENERATED INFO
// =====================================================

export function addGeneratedInfo({

  pdf,

  generatedBy =
    EXPORT_CONFIG.generatedBy

}) {

  const pageWidth =
    pdf.internal.pageSize.width

  const now =
    new Date()

  pdf.setFontSize(8)

  pdf.text(

    `Generated: ${now.toLocaleString()}`,

    pageWidth - 70,

    15

  )

  pdf.text(

    `Generated By: ${generatedBy}`,

    pageWidth - 70,

    20

  )

}

// =====================================================
// FILTERS SECTION
// =====================================================

export function addFiltersSection({

  pdf,

  filters = {}

}) {

  let y = 38

  const entries =
    Object.entries(
      filters
    )

  if (
    entries.length === 0
  ) {

    return y

  }

  pdf.setFontSize(10)

  pdf.text(
    'Filters Applied',
    14,
    y
  )

  y += 6

  entries.forEach(

    ([key, value]) => {

      pdf.text(

        `${key}: ${value}`,

        18,

        y

      )

      y += 5

    }

  )

  return y

}

// =====================================================
// SUMMARY SECTION
// =====================================================

export function addSummarySection({

  pdf,

  summary = {},

  startY = 40

}) {

  const entries =
    Object.entries(
      summary
    )

  if (
    entries.length === 0
  ) {

    return startY

  }

  pdf.setFontSize(10)

  pdf.text(
    'Summary',
    14,
    startY
  )

  let y =
    startY + 6

  entries.forEach(

    ([key, value]) => {

      pdf.text(

        `${key}: ${value}`,

        18,

        y

      )

      y += 5

    }

  )

  return y

}

// =====================================================
// TABLE
// =====================================================

export function addTable({

  pdf,

  columns = [],

  data = [],

  startY = 50

}) {

  autoTable(
    pdf,
    {

      startY,

      head: [

        columns.map(
          column =>
            column.label
        )

      ],

      body:

        data.map(
          row =>

            columns.map(
              column =>

                row[
                  column.key
                ] ?? ''
            )
        ),

      styles: {

        fontSize:
          8

      },

      headStyles: {

        fillColor:
          [60, 120, 60]

      }

    }
  )

  return (
    pdf.lastAutoTable
      ?.finalY || startY
  )

}

// =====================================================
// FOOTER
// =====================================================

export function addFooter(
  pdf
) {

  const pageCount =
    pdf.internal
      .getNumberOfPages()

  for (

    let page = 1;

    page <= pageCount;

    page++

  ) {

    pdf.setPage(
      page
    )

    const width =
      pdf.internal
        .pageSize
        .getWidth()

    const height =
      pdf.internal
        .pageSize
        .getHeight()

    pdf.setFontSize(
      8
    )

    pdf.text(

      EXPORT_CONFIG.reportFooter,

      14,

      height - 8

    )

    pdf.text(

      `Page ${page} of ${pageCount}`,

      width - 35,

      height - 8

    )

  }

}

// =====================================================
// SAVE
// =====================================================

export function savePdf({

  pdf,

  reportName

}) {

  pdf.save(

    `${buildFileName(
      reportName
    )}.pdf`

  )

}

// =====================================================
// SIMPLE REPORT
// =====================================================

export function downloadPdf({

  reportName,

  columns,

  data,

  filters = {},

  summary = {},

  orientation =
    'landscape'

}) {

  const pdf =
    createPdf({

      orientation

    })

  addReportHeader({

    pdf,

    reportTitle:
      reportName

  })

  addGeneratedInfo({
    pdf
  })

  let currentY =
    addFiltersSection({

      pdf,

      filters

    })

  currentY =
    addSummarySection({

      pdf,

      summary,

      startY:
        currentY + 5

    })

  addTable({

    pdf,

    columns,

    data,

    startY:
      currentY + 10

  })

  addFooter(
    pdf
  )

  savePdf({

    pdf,

    reportName

  })

}

// =====================================================
// IMPORT ERROR REPORT
// =====================================================

export function downloadPdfErrors({

  reportName,

  errors = []

}) {

  const columns = [

    {
      key: 'row',
      label: 'Row'
    },

    {
      key: 'field',
      label: 'Field'
    },

    {
      key: 'value',
      label: 'Value'
    },

    {
      key: 'message',
      label: 'Error'
    }

  ]

  downloadPdf({

    reportName,

    columns,

    data:
      errors

  })

}

// =====================================================
// SUMMARY REPORT
// =====================================================

export function downloadSummaryPdf({

  reportName,

  summary

}) {

  const pdf =
    createPdf()

  addReportHeader({

    pdf,

    reportTitle:
      reportName

  })

  addGeneratedInfo({
    pdf
  })

  addSummarySection({

    pdf,

    summary,

    startY: 40

  })

  addFooter(
    pdf
  )

  savePdf({

    pdf,

    reportName

  })

}