// =====================================================
// EVENT IMPORT
// ParaCycling Federation Management System
// =====================================================

import {

    process,

    commit,

    finish

} from '../import/importService.js'

import {

    buildPreview

}

from '../import/previewImporter.js'
import {

    COMMIT_FIELDS,

    buildCommitObject

}

from '../import/importHelpers.js'

import {

    buildSummary,

    downloadFullPackage

}

from '../import/importErrors.js'


// =====================================================
// EVENT FIELD MAP
//
// Central definition of every Event Import field.
//
// All builders, validators, lookups and commit plans
// must reference these constants.
//
// =====================================================

const EVENT_FIELDS = Object.freeze({

    EVENT_CATEGORY_CODE:
        'event_category_code',

    EVENT_TYPE_CODE:
        'event_type_code',

    EVENT_STATUS_CODE:
        'event_status_code',

    SPONSOR_CODE:
        'sponsor_code',

    TOWN_NAME:
        'town_name',

    ORGANIZER:
        'organizer',
    NOTES:
       'notes',

    START_DATE:
        'start_date',

    END_DATE:
        'end_date',

    START_TIME:
        'start_time',

    END_TIME:
        'end_time'

})


// =====================================================
// GENERATED FIELDS
//
// Values generated by the importer.
//
// Never supplied by the CSV.
//
// =====================================================

const GENERATED_FIELDS = Object.freeze({

    EVENT_CODE:

        'event_code',

    EVENT_NAME:

        'event_name',

    EVENT_AREA:

        'event_area',

    COUNTRY_ID:

        'country_id'

})



const IMPORT_FIELDS = Object.freeze({

    EVENT_ID:

        'event_id',

    EVENT_CODE:

        'event_code'

})

// =====================================================
// EVENT TABLES
// =====================================================

const EVENT_TABLES = Object.freeze({

    EVENTS:

        'events',

    OCCURRENCES:

        'event_instances',

    SPONSORS:

        'event_sponsors'

})


// =====================================================
// DEFAULT IMPORT OPTIONS
// =====================================================

const DEFAULT_OPTIONS = Object.freeze({

    chunkSize: 500,

    ignoreDuplicates: false,

    returning: true

})








// =====================================================
// IMPORT EVENTS
//
// Public entry point.
//
// CSV
//      ↓
// process()
//      ↓
// validateEvent()
//      ↓
// resolveEvent()
//      ↓
// buildCommitPlan()
//      ↓
// commit()
//      ↓
// finish()
//
// =====================================================

export async function importEvents(

    file

) {

    const result =

        await process({

            file,

            validator:

                validateEvent,

            resolver:

                resolveEvent,

            commitPlanBuilder:

                buildCommitPlan

        })

    const preview =

        buildPreview(

            result

        )

    return {

        stage:

            'preview',

        preview,

        approve:

            async () => {

                const context =

                    begin()

                const commitResult =

                    await commit(

                        context,

                        result.commitPlan

                    )

                const finished =

                    finish(

                        commitResult

                    )

                const report = {

                    module:

                        'Events',

                    source:

                        result.raw?.source,

                    startedAt:

                        finished.startedAt,

                    completedAt:

                        finished.completedAt,

                    summary: {

                        totalRows:

                            result.normalized?.totalRows || 0,

                        importedRows:

                            finished.committed || 0,

                        warningRows:

                            result.resolved?.warnings?.length || 0,

                        errorRows:

                            finished.errors?.length || 0

                    },

                    warnings:

                        result.resolved?.warnings || [],

                    errors:

                        [

                            ...(result.resolved?.errors || []),

                            ...(finished.errors || [])

                        ]

                }

                return {

                    ...finished,

                    summary:

                        buildSummary(

                            report

                        ),

                    downloads:

                        await downloadFullPackage(

                            report

                        )

                }

            }

    }

}
// =====================================================
// EVENT VALIDATION
//
// Contains ONLY event business rules.
//
// Uses the generic validation library already
// supplied by importService.
//
// No generic validation code belongs here.
//
// =====================================================

export async function validateEvent(

    importData,

    validation

) {

    const errors = []

    validateRequiredFields(

        importData,

        validation,

        errors

    )

    validateEventDates(

        importData,

        validation,

        errors

    )

    validateDuplicateEvents(

        importData,

        validation,

        errors

    )

    return {

        ...importData,

        valid:

            errors.length === 0,

        errors

    }

}

// =====================================================
// REQUIRED FIELD VALIDATION
// =====================================================

function validateRequiredFields(

    importData,

    validation,

    errors

) {

    for (

        const [

            index,

            row

        ]

        of (

            importData.objects || []

        ).entries()

    ) {

        const requiredFields = [

    [
        'town_name',
        'Town'
    ],

    [
        'event_category_code',
        'Event Category'
    ],

    [
        'event_type_code',
        'Event Type'
    ],

    [
        'event_status_code',
        'Event Status'
    ],

    [
        'start_date',
        'Start Date'
    ],

    [
        'end_date',
        'End Date'
    ]

]

        for (

            const [

                field,

                label

            ]

            of requiredFields

        ) {

            const result =

                validation.validateRequired(

                    row[field],

                    label

                )

            if (

                !result.valid

            ) {

                errors.push({

                    row:

                        index + 1,

                    field,

                    message:

                        result.message

                })

            }

        }

    }

}

// =====================================================
// EVENT DATE VALIDATION
// =====================================================

function validateEventDates(

    importData,

    validation,

    errors

) {

    for (

        const [

            index,

            row

        ]

        of (

            importData.objects || []

        ).entries()

    ) {

        const startDate =

            validation.validateDate(

                row.start_date

            )

        if (

            !startDate.valid

        ) {

            errors.push({

                row:

                    index + 1,

                field:

                    'start_date',

                message:

                    startDate.message

            })

        }

        const endDate =

            validation.validateDate(

                row.end_date

            )

        if (

            !endDate.valid

        ) {

            errors.push({

                row:

                    index + 1,

                field:

                    'end_date',

                message:

                    endDate.message

            })

        }

        if (

            row.start_date &&

            row.end_date &&

            new Date(

                row.end_date

            ) <

            new Date(

                row.start_date

            )

        ) {

            errors.push({

                row:

                    index + 1,

                field:

                    'end_date',

                message:

                    'End Date cannot be earlier than Start Date.'

            })

        }

    }

}

// =====================================================
// DUPLICATE EVENT VALIDATION
// =====================================================

function validateDuplicateEvents(

    importData,

    validation,

    errors

) {

    const duplicates =

        validation.validateDuplicates(

            importData.objects || [],

            [
    'town_name',
    'event_type_code',
    'event_category_code',
    'start_date',
    'start_time'
]
        )

    if (

        !duplicates.valid

    ) {

        errors.push(

            ...(duplicates.value || [])

        )

    }

}

// =====================================================
// LOOKUP VALIDATION
// =====================================================
//
// Placeholder.
//
// This executes AFTER lookup resolution.
//
// It validates:
//
// Town
// Event Type
// Event Category
// Status
// Sponsor
//
// using the resolver results.
//
// =====================================================

function validateLookupFields(

    resolvedData,

    errors

) {

    for (

        const [

            index,

            row

        ]

        of (

            resolvedData.objects || []

        ).entries()

    ) {

        validateLookup(

            index,

            row,

            'town',

            'Town',

            errors

        )

        validateLookup(

            index,

            row,

            'category',

            'Event Category',

            errors

        )

        validateLookup(

            index,

            row,

            'eventType',

            'Event Type',

            errors

        )

        validateLookup(

            index,

            row,

            'status',

            'Status',

            errors

        )

        if (

            row.sponsor

        ) {

            validateLookup(

                index,

                row,

                'sponsor',

                'Sponsor',

                errors

            )

        }

    }

    return errors

}

function validateLookup(

    rowIndex,

    row,

    property,

    label,

    errors

) {

    const lookup =

        row[
            property
        ]

    if (

        lookup?.found

    ) {

        return

    }

    errors.push({

        row:

            rowIndex + 1,

        field:

            property,

        message:

            `${label} was not found.`

    })

}




// =====================================================
// EVENT LOOKUP RESOLUTION
//
// Resolves:
//
// County
// Subcounty
// Town
// Event Category
// Event Type
// Status
// Sponsor
//
// Uses lookupResolver.
//
// No SQL.
//
// =====================================================

export async function resolveEvent(

    validatedData,

    lookup

) {

    const resolvedObjects = []

    for (

        const importObject

        of validatedData.objects || []

    ) {

        const resolvedObject =

            await resolveImportObject(

                importObject,

                lookup

            )

        const generatedObject =

            generateDerivedFields(

                resolvedObject

            )

        resolvedObjects.push(

            buildCommitObject(

                generatedObject

            )

        )

    }

    const resolvedData = {

        ...validatedData,

        objects:

            resolvedObjects

    }

    const errors = [

        ...(validatedData.errors || [])

    ]

    validateLookupFields(

        resolvedData,

        errors

    )

    return {

        ...resolvedData,

        valid:

            errors.length === 0,

        errors

    }

}

// =====================================================
// RESOLVE IMPORT OBJECT
//
// Converts an Import Object into a fully
// Resolved Object.
//
// =====================================================

async function resolveImportObject(

    importObject = {},

    lookup

) {

    const town =

        await lookup.resolveTown(

            importObject.town_name

        )

    const subcounty =

    town.record

        ? await lookup.resolveSubcountyById(

            town.record.subcounty_id

        )

        : {

            found: false,

            id: null,

            record: null

        }

const county =

    subcounty.record

        ? await lookup.resolveCountyById(

            subcounty.record.county_id

        )

        : {

            found: false,

            id: null,

            record: null

        }

const country =

    county.record

        ? await lookup.resolveCountryById(

            county.record.country_id

        )

        : {

            found: false,

            id: null,

            record: null

        }

    const eventType =

    await lookup.resolveEventTypeCode(

        importObject.event_type_code

    )

    const category =

        await lookup.resolveCategoryCode(

    importObject.event_category_code

)

        

    const status =

        await lookup.resolveEventStatusCode(

    importObject.event_status_code

)
        

  const sponsor =

    await lookup.resolveSponsorCode(

        importObject.sponsor_code

    )



    return {

    ...importObject,

    town,

    subcounty,

    county,

    country,

    eventType,

    category,

    status,

    sponsor,

    

}

}
// =====================================================
// GENERATE DERIVED FIELDS
//
// Generates fields that are not supplied by the CSV.
//
// =====================================================

// =====================================================
// GENERATE DERIVED FIELDS
//
// Converts a Resolved Object into a
// Generated Object.
//
// =====================================================

function generateDerivedFields(

    resolvedObject = {}

) {

    return {

    ...resolvedObject,

    [GENERATED_FIELDS.COUNTRY_ID]:

        resolvedObject.country?.id ?? null,

    [GENERATED_FIELDS.EVENT_NAME]:

        [

            resolvedObject.town?.name,

            resolvedObject.eventType?.name

        ]

        .filter(Boolean)

        .join(' '),

    [GENERATED_FIELDS.EVENT_AREA]:

        [

            resolvedObject.town?.name,

            resolvedObject.eventType?.name

        ]

        .filter(Boolean)

        .join(' ')

}

}

// =====================================================
// BUILD COMMIT OBJECT
//
// Converts a Generated Object into the
// exact structure expected by the builders.
//
// =====================================================





// =====================================================
// BUILD EVENT MASTER
//
// Builds unique records for:
//
// events
//
// =====================================================

function buildEventMaster(

    resolvedData = {}

) {

    const records =

        uniqueEvents(

            resolvedData.objects || []

        )

   return {

    table:

        EVENT_TABLES.EVENTS,

    operation:

    'upsert',

records,

conflictColumn:

    'event_name',

options:

    DEFAULT_OPTIONS,

    identity: {

        collection:

            'events',

        databaseKey:

            'event_id',

       businessKey(

    record

) {

    if (

        record[
            IMPORT_FIELDS.EVENT_ID
        ]

    ) {

        return `ID:${
            record[
                IMPORT_FIELDS.EVENT_ID
            ]
        }`

    }

    if (

        record[
            IMPORT_FIELDS.EVENT_CODE
        ]

    ) {

        return `CODE:${
            record[
                IMPORT_FIELDS.EVENT_CODE
            ]
        }`

    }

    return [

        record[
            COMMIT_FIELDS.TOWN_ID
        ],

        record[
            COMMIT_FIELDS.EVENT_CATEGORY_ID
        ],

        record[
            COMMIT_FIELDS.EVENT_TYPE_ID
        ]

    ].join('|')

}

    }

}

}


// =====================================================
// BUILD EVENT OCCURRENCES
//
// Builds records for:
//
// event_instances
//
// =====================================================

function buildOccurrences(

    resolvedData = {}

) {

    const records =

        extractOccurrences(

            resolvedData.objects || []

        )

    return {

        table:

            EVENT_TABLES.OCCURRENCES,

       operation:

    'upsert',

records,

conflictColumn:

    'event_id,event_area,start_date,start_time',

        options:

            DEFAULT_OPTIONS,

        identity: {

            collection:

                'occurrences',

            databaseKey:

                'event_instance_id',

            businessKey(

    record

) {

    if (

        record.event_instance_id

    ) {

        return `INSTANCE:${
            record.event_instance_id
        }`

    }

    return [

    record[
        COMMIT_FIELDS.TOWN_ID
    ],

    record[
        COMMIT_FIELDS.EVENT_CATEGORY_ID
    ],

    record[
        COMMIT_FIELDS.EVENT_TYPE_ID
    ],

    record[
        GENERATED_FIELDS.EVENT_AREA
    ],

    record[
        EVENT_FIELDS.START_DATE
    ],

    record[
        EVENT_FIELDS.START_TIME
    ]

].join('|')

}

        },

        foreignKeys: [

            {

                field:

                    'event_id',

                identity:

                    'events',

                businessKey(

                    record

                ) {

                    return [

                        record[
                            COMMIT_FIELDS.TOWN_ID
                        ],

                        record[
                            COMMIT_FIELDS.EVENT_CATEGORY_ID
                        ],

                        record[
                            COMMIT_FIELDS.EVENT_TYPE_ID
                        ]

                    ].join('|')

                }

            }

        ]

    }

}


// =====================================================
// BUILD EVENT SPONSORS
//
// Optional.
//
// =====================================================

function buildSponsors(

    resolvedData = {}

) {

    const records =

        extractSponsors(

            resolvedData.objects || []

        )

    return {

        table:

            EVENT_TABLES.SPONSORS,

        operation:

    'upsert',

records,

conflictColumn:

    'event_instance_id,sponsor_id',

        options:

            DEFAULT_OPTIONS,

        identity: {

            collection:

                'eventSponsors',

            databaseKey:

                'event_sponsor_id',

           businessKey(

    record

) {

    if (

        record.event_sponsor_id

    ) {

        return `SPONSOR:${
            record.event_sponsor_id
        }`

    }

    return [

    record[
        COMMIT_FIELDS.TOWN_ID
    ],

    record[
        COMMIT_FIELDS.EVENT_CATEGORY_ID
    ],

    record[
        COMMIT_FIELDS.EVENT_TYPE_ID
    ],

    record[
        GENERATED_FIELDS.EVENT_AREA
    ],

    record[
        EVENT_FIELDS.START_DATE
    ],

    record[
        EVENT_FIELDS.START_TIME
    ]

].join('|')
}

        },

        foreignKeys: [

            {

                field:

                    'event_instance_id',

                identity:

                    'occurrences',

                businessKey(

                    record

                ) {

                    return [

    record[
        COMMIT_FIELDS.TOWN_ID
    ],

    record[
        COMMIT_FIELDS.EVENT_CATEGORY_ID
    ],

    record[
        COMMIT_FIELDS.EVENT_TYPE_ID
    ],

    record[
        GENERATED_FIELDS.EVENT_AREA
    ],

    record[
        EVENT_FIELDS.START_DATE
    ],

    record[
        EVENT_FIELDS.START_TIME
    ],

    record[
        COMMIT_FIELDS.SPONSOR_ID
    ]

].join('|')

                }

            }

        ]

    }

}

// =====================================================
// COLLECT OPERATIONS
//
// =====================================================

function collectOperations(

    resolvedData = {}

) {

    return [

        buildEventMaster(

            resolvedData

        ),

        buildOccurrences(

            resolvedData

        ),

        buildSponsors(

            resolvedData

        )

    ].filter(

        operation =>

            operation.records.length > 0

    )

}


export function buildCommitPlan(

    resolvedData = {}

) {

    return {

        stages: [

            {

                name:

                    'events',

                operations: [

                    buildEventMaster(

                        resolvedData

                    )

                ]

            },

            {

                name:

                    'occurrences',

                dependsOn: [

                    'events'

                ],

                operations: [

                    buildOccurrences(

                        resolvedData

                    )

                ]

            },

            {

                name:

                    'sponsors',

                dependsOn: [

                    'occurrences'

                ],

                operations: [

                    buildSponsors(

                        resolvedData

                    )

                ]

            }

        ]

    }

}

// =====================================================
// UNIQUE EVENTS
//
// Groups duplicate event masters.
//
// =====================================================

function uniqueEvents(

    objects = []

) {

    const events =

        new Map()

    objects.forEach(

        object => {

           const businessKey = [

    object[
       COMMIT_FIELDS.TOWN_ID
    ],

    object[
        COMMIT_FIELDS.EVENT_TYPE_ID
    ],

    object[
        COMMIT_FIELDS.EVENT_CATEGORY_ID
    ]

].join('|')

events.set(

    businessKey,

    {

        event_name:

            object[
                GENERATED_FIELDS.EVENT_NAME
            ],

        event_category_id:

            object[
                COMMIT_FIELDS.EVENT_CATEGORY_ID
            ],

        event_type_id:

            object[
                COMMIT_FIELDS.EVENT_TYPE_ID
            ]

    }

)

        }

    )

    return [

        ...events.values()

    ]

}




// =====================================================
// EXTRACT OCCURRENCES
//
// =====================================================

function extractOccurrences(

    objects = []

) {

    return objects.map(

        object => ({

            event_id:

                null,

            

            country_id:

                object[
                    COMMIT_FIELDS.COUNTRY_ID
                ],

            county_id:

                object[
                    COMMIT_FIELDS.COUNTY_ID
                ],

            subcounty_id:

                object[
                    COMMIT_FIELDS.SUBCOUNTY_ID
                ],

            town_id:

                object[
                    COMMIT_FIELDS.TOWN_ID
                ],
            organizer:

    object[
        EVENT_FIELDS.ORGANIZER
    ],

notes:

    object[
        EVENT_FIELDS.NOTES
    ],

event_area:

                object[
                    GENERATED_FIELDS.EVENT_AREA
                ],

            
           
            

            sponsor_id:

                object[
                    COMMIT_FIELDS.SPONSOR_ID
                ],

            start_date:

    object[
        EVENT_FIELDS.START_DATE
    ],

end_date:

    object[
        EVENT_FIELDS.END_DATE
    ],


start_time:

    object[
        EVENT_FIELDS.START_TIME
    ] || '06:00',

end_time:

    object[
        EVENT_FIELDS.END_TIME
    ] || '18:00'




        })

    )

}
// =====================================================
// EXTRACT SPONSORS
//
// =====================================================

function extractSponsors(

    objects = []

) {

    return objects

        .filter(

            object =>

                object[
                    COMMIT_FIELDS.SPONSOR_ID
                ]

        )

        .map(

            object => ({

                event_instance_id:

                    null,

                sponsor_id:

                    object[
                        COMMIT_FIELDS.SPONSOR_ID
                    ],

                country_id:

                    object[
                        COMMIT_FIELDS.COUNTRY_ID
                    ],

                county_id:

                    object[
                        COMMIT_FIELDS.COUNTY_ID
                    ],

                subcounty_id:

                    object[
                        COMMIT_FIELDS.SUBCOUNTY_ID
                    ],

                town_id:

                    object[
                        COMMIT_FIELDS.TOWN_ID
                    ],

                event_category_id:

                    object[
                        COMMIT_FIELDS.EVENT_CATEGORY_ID
                    ],

                event_type_id:

                    object[
                        COMMIT_FIELDS.EVENT_TYPE_ID
                    ],

                

            })

        )

}