// =====================================================
// EVENT IMPORT
// ParaCycling Federation Management System
// =====================================================

import {

  process,

  commit,

  finish

} from '../import/importService.js'

import {

  buildPreview

}

  from '../import/previewImporter.js'
import {

  COMMIT_FIELDS,

  buildCommitObject

}

  from '../import/importHelpers.js'

import {

  buildSummary,

  downloadFullPackage

}

  from '../import/importErrors.js'

import {

  findOrCreateTown

}

  from '../services/locationLookupService.js'
// =====================================================
// EVENT FIELD MAP
//
// Central definition of every Event Import field.
//
// All builders, validators, lookups and commit plans
// must reference these constants.
//
// =====================================================

const EVENT_FIELDS = Object.freeze({

  EVENT_CODE:
    'event_code',

  SPONSOR_CODE:
        'sponsor_code',
  SUBCOUNTY_NAME:
    'subcounty_code',

  TOWN_NAME:
        'town_name',

  ORGANIZER:
        'organizer',
  NOTES:
       'notes',

  START_DATE:
        'start_date',

  END_DATE:
        'end_date',

  START_TIME:
        'start_time',

  END_TIME:
        'end_time'

})

// =====================================================
// GENERATED FIELDS
//
// Values generated by the importer.
//
// Never supplied by the CSV.
//
// =====================================================

const GENERATED_FIELDS = Object.freeze({

  EVENT_CODE:

        'event_code',

  EVENT_NAME:

        'event_name',

  EVENT_AREA:

        'event_area',

  COUNTRY_ID:

        'country_id'

})

const IMPORT_FIELDS = Object.freeze({

  EVENT_ID:

        'event_id',

  EVENT_CODE:

        'event_code'

})

// =====================================================
// EVENT TABLES
// =====================================================

const EVENT_TABLES = Object.freeze({

  EVENTS:

        'events',

  OCCURRENCES:

        'event_instances',

  SPONSORS:

        'event_sponsors'

})

// =====================================================
// DEFAULT IMPORT OPTIONS
// =====================================================

const DEFAULT_OPTIONS = Object.freeze({

  chunkSize: 500,

  ignoreDuplicates: false,

  returning: true

})

// =====================================================
// IMPORT EVENTS
//
// Public entry point.
//
// CSV
//      ↓
// process()
//      ↓
// validateEvent()
//      ↓
// resolveEvent()
//      ↓
// buildCommitPlan()
//      ↓
// commit()
//      ↓
// finish()
//
// =====================================================

export async function importEvents(

  file

) {
  const result =

        await process({

          file,

          validator:

                validateEvent,

          resolver:

                resolveEvent,

          commitPlanBuilder:

                buildCommitPlan

        })

  const preview =

    result.preview

  return {

    stage:

            'preview',

    preview,

    approve:

            async () => {
              const commitResult =

    await commit(

      result.commitPlan

    )
              const finished =

                    finish(

                      commitResult

                    )

              const report = {

                module:

                        'Events',

                source:

                        result.raw?.source,

                startedAt:

                        finished.startedAt,

                completedAt:

                        finished.completedAt,

                summary: {

                  totalRows:

                            result.normalized?.totalRows || 0,

                  importedRows:

                            finished.committed || 0,

                  warningRows:

                            result.resolved?.warnings?.length || 0,

                  errorRows:

                            finished.errors?.length || 0

                },

                warnings:

                        result.resolved?.warnings || [],

                errors:

                        [

                          ...(result.resolved?.errors || []),

                          ...(finished.errors || [])

                        ]

              }

              return {

                ...finished,

                summary:

                        buildSummary(

                          report

                        ),

                downloads:

                        await downloadFullPackage(

                          report

                        )

              }
            }

  }
}
// =====================================================
// EVENT VALIDATION
//
// Contains ONLY event business rules.
//
// Uses the generic validation library already
// supplied by importService.
//
// No generic validation code belongs here.
//
// =====================================================

export async function validateEvent(

  importData,

  validation

) {
  const errors = []

  validateRequiredFields(

    importData,

    validation,

    errors

  )

  validateEventDates(

    importData,

    validation,

    errors

  )

  validateDuplicateEvents(

    importData,

    validation,

    errors

  )

  return {

    ...importData,

    valid:

            errors.length === 0,

    errors

  }
}

// =====================================================
// REQUIRED FIELD VALIDATION
// =====================================================

function validateRequiredFields(

  importData,

  validation,

  errors

) {
  for (

    const [

      index,

      row

    ]

    of (

      importData.objects || []

    ).entries()

  ) {
    const requiredFields = [

      [
        EVENT_FIELDS.EVENT_CODE,
        'Event Code'
      ],

      [
        EVENT_FIELDS.SUBCOUNTY_NAME,
        'Subcounty'
      ],

      [
        EVENT_FIELDS.TOWN_NAME,
        'Town'
      ],

      [
        EVENT_FIELDS.START_DATE,
        'Start Date'
      ],

      [
        EVENT_FIELDS.END_DATE,
        'End Date'
      ]

    ]

    for (

      const [

        field,

        label

      ]

      of requiredFields

    ) {
      const result =

                validation.validateRequired(

                  row[field],

                  label

                )

      if (

        !result.valid

      ) {
        errors.push({

          row:

                        index + 1,

          field,

          message:

                        result.message

        })
      }
    }
  }
}

// =====================================================
// EVENT DATE VALIDATION
// =====================================================

function validateEventDates(

  importData,

  validation,

  errors

) {
  for (

    const [

      index,

      row

    ]

    of (

      importData.objects || []

    ).entries()

  ) {
    const startDate =

            validation.validateDate(

              row.start_date

            )

    if (

      !startDate.valid

    ) {
      errors.push({

        row:

                    index + 1,

        field:

                    'start_date',

        message:

                    startDate.message

      })
    }

    const endDate =

            validation.validateDate(

              row.end_date

            )

    if (

      !endDate.valid

    ) {
      errors.push({

        row:

                    index + 1,

        field:

                    'end_date',

        message:

                    endDate.message

      })
    }

    if (

      row.start_date &&

            row.end_date &&

            new Date(

              row.end_date

            ) <

            new Date(

              row.start_date

            )

    ) {
      errors.push({

        row:

                    index + 1,

        field:

                    'end_date',

        message:

                    'End Date cannot be earlier than Start Date.'

      })
    }
  }
}

// =====================================================
// DUPLICATE EVENT VALIDATION
// =====================================================

function validateDuplicateEvents(

  importData,

  validation,

  errors

) {
  const duplicates =

        validation.validateDuplicates(

          importData.objects || [],

          [
            'event_code',
            'town_name',
            'start_date',
            'start_time'
          ]
        )

  if (

    !duplicates.valid

  ) {
    errors.push(

      ...(duplicates.value || [])

    )
  }
}

// =====================================================
// LOOKUP VALIDATION
// =====================================================
//
// Placeholder.
//
// This executes AFTER lookup resolution.
//
// It validates:
//
// Town
// Event Type
// Event Category
// Status
// Sponsor
//
// using the resolver results.
//
// =====================================================

function validateLookupFields(

  resolvedData,

  errors

) {
  for (

    const [

      index,

      row

    ]

    of (

      resolvedData.objects || []

    ).entries()

  ) {
    validateLookup(

      index,

      row,

      'subcounty',

      'Subcounty',

      errors

    )

    validateLookup(

      index,

      row,

      'town',

      'Town',

      errors

    )

    validateLookup(

      index,

      row,

      'event',

      'Event',

      errors

    )

    if (

      row.sponsor

    ) {
      validateLookup(

        index,

        row,

        'sponsor',

        'Sponsor',

        errors

      )
    }
  }

  return errors
}

function validateLookup(

  rowIndex,

  row,

  property,

  label,

  errors

) {
  const lookup =

        row[
            property
        ]

  if (

    lookup?.found

  ) {
    return
  }

  errors.push({

    row:

            rowIndex + 1,

    field:

            property,

    message:

            `${label} was not found.`

  })
}

// =====================================================
// EVENT LOOKUP RESOLUTION
//
// Resolves:
//
// County
// Subcounty
// Town
// Event Category
// Event Type
// Status
// Sponsor
//
// Uses lookupResolver.
//
// No SQL.
//
// =====================================================

export async function resolveEvent(

  validatedData,

  lookup

) {
  const resolvedObjects = []
  const commitObjects = []

  for (

    const importObject

    of validatedData.objects || []

  ) {
    const resolvedObject =

            await resolveImportObject(

              importObject,

              lookup

            )

    const generatedObject =

    generateDerivedFields(

      resolvedObject

    )

    resolvedObjects.push(
      resolvedObject
    )

    commitObjects.push(

      buildCommitObject(

        generatedObject

      )

    )
  }

  const resolvedData = {

    ...validatedData,

    objects:

        resolvedObjects,

    commitObjects

  }

  const errors = [

    ...(validatedData.errors || [])

  ]

  validateLookupFields(

    resolvedData,

    errors

  )

  return {

    ...resolvedData,

    valid:

            errors.length === 0,

    errors

  }
}

// =====================================================
// EMPTY LOOKUP
//
// Standard empty lookup object used whenever
// a resolver cannot continue because a parent
// lookup failed.
//
// =====================================================

function emptyLookup() {
  return {

    found: false,

    id: null,

    code: null,

    name: null,

    record: null

  }
}
// =====================================================
// RESOLVE IMPORT OBJECT
//
// Converts an Import Object into a fully
// Resolved Object.
//
// =====================================================

async function resolveImportObject(

  importObject = {},

  lookup

) {
  // ==========================================
  // Resolve Event
  // ==========================================

  const event =

        await lookup.resolveEventCode(

          importObject.event_code

        )

  // ==========================================
  // Resolve Sponsor
  // ==========================================

  const sponsor =

        await lookup.resolveSponsorCode(

          importObject.sponsor_code

        )

  // ==========================================
  // Resolve Subcounty
  // ==========================================

  const subcountyValue =

    importObject.subcounty_code

  const subcounty =

    subcountyValue?.includes('-') ?

      await lookup.resolveSubcountyCode(

        subcountyValue

      ) :

      await lookup.resolveSubcounty(

        subcountyValue

      )

  // ==========================================
  // Resolve County
  // ==========================================

  const county =

        subcounty.found ?

          await lookup.resolveCountyById(

            subcounty.record.county_id

          ) :

          emptyLookup()

  // ==========================================
  // Resolve Country
  // ==========================================

  const country =

        county.found ?

          await lookup.resolveCountryById(

            county.record.country_id

          ) :

          emptyLookup()

  // ==========================================
  // Resolve / Create Town
  // ==========================================

  const town =

    subcounty.found ?

      await findOrCreateTown({

        townName:

                importObject.town_name,

        subcountyId:

                subcounty.id

      }) :

      emptyLookup()

  // ==========================================
  // Return Resolved Object
  // ==========================================

  return {

    ...importObject,

    event,

    sponsor,

    subcounty,

    county,

    country,

    town

  }
}
// =====================================================
// GENERATE DERIVED FIELDS
//
// Generates fields that are not supplied by the CSV.
//
// =====================================================

// =====================================================
// GENERATE DERIVED FIELDS
//
// Converts a Resolved Object into a
// Generated Object.
//
// =====================================================
function generateDerivedFields(

  resolvedObject = {}

) {
  return {

    ...resolvedObject,

    [GENERATED_FIELDS.COUNTRY_ID]:

            resolvedObject.country?.id ?? null,

    [GENERATED_FIELDS.EVENT_NAME]:

            resolvedObject.event
                ?.record
                ?.event_name || '',

    [GENERATED_FIELDS.EVENT_AREA]:

            [

              resolvedObject.town?.name,

              resolvedObject.event
                    ?.record
                    ?.event_type_master
                    ?.event_type_name

            ]

            .filter(Boolean)

            .join(' ')

  }
}
// =====================================================
// BUILD COMMIT OBJECT
//
// Converts a Generated Object into the
// exact structure expected by the builders.
//
// =====================================================

// =====================================================
// BUILD EVENT MASTER
//
// Builds unique records for:
//
// events
//
// =====================================================

// =====================================================
// BUILD EVENT OCCURRENCES
//
// Builds records for:
//
// event_instances
//
// =====================================================

function buildOccurrences(

  resolvedData = {}

) {
  const records =

    extractOccurrences(

      resolvedData.commitObjects ||

        resolvedData.objects ||

        []

    )
  return {

    table:

            EVENT_TABLES.OCCURRENCES,

    operation:

    'upsert',

    records,

    conflictColumn:

    'event_id,event_area,start_date,start_time',

    options:

            DEFAULT_OPTIONS,

    identity: {

      collection:

                'occurrences',

      databaseKey:

                'event_instance_id',

      businessKey(

        record

      ) {
        if (

          record.event_instance_id

        ) {
          return `INSTANCE:${
            record.event_instance_id
          }`
        }

        return [

          record[
        COMMIT_FIELDS.EVENT_ID
          ],

          record[
        COMMIT_FIELDS.TOWN_ID
          ],

          record[
        EVENT_FIELDS.START_DATE
          ],

          record[
        EVENT_FIELDS.START_TIME
          ]

        ].join('|')
      }

    },

    foreignKeys: []

  }
}

function buildSponsors() {
  return {
    table: EVENT_TABLES.SPONSORS,
    operation: 'insert',
    records: []
  }
}

// =====================================================
// COLLECT OPERATIONS
//
// =====================================================

function collectOperations(

  resolvedData = {}

) {
  return [

    buildOccurrences(

      resolvedData

    ),

    buildSponsors(

      resolvedData

    )

  ].filter(

    operation =>

      operation.records.length > 0

  )
}

export function buildCommitPlan(

  resolvedData = {}

) {
  return {

    stages: [

      {

        name:

                    'occurrences',

        dependsOn: [],

        operations: [

          buildOccurrences(

            resolvedData

          )

        ]

      },

      {

        dependsOn: [],

        operations: [

        ]

      }

    ]

  }
}

// =====================================================
// EXTRACT OCCURRENCES
//
// =====================================================

function extractOccurrences(

  objects = []

) {
  return objects.map(

    object => ({

      event_id:

    object[
        COMMIT_FIELDS.EVENT_ID
    ],

      country_id:

                object[
                    COMMIT_FIELDS.COUNTRY_ID
                ],

      county_id:

                object[
                    COMMIT_FIELDS.COUNTY_ID
                ],

      subcounty_id:

                object[
                    COMMIT_FIELDS.SUBCOUNTY_ID
                ],

      town_id:

                object[
                    COMMIT_FIELDS.TOWN_ID
                ],
      organizer:

    object[
        EVENT_FIELDS.ORGANIZER
    ],

      notes:

    object[
        EVENT_FIELDS.NOTES
    ],

      event_area:

                object[
                    GENERATED_FIELDS.EVENT_AREA
                ],

      sponsor_id:

                object[
                    COMMIT_FIELDS.SPONSOR_ID
                ],

      start_date:

    object[
        EVENT_FIELDS.START_DATE
    ],

      end_date:

    object[
        EVENT_FIELDS.END_DATE
    ],

      start_time:

    object[
        EVENT_FIELDS.START_TIME
    ] || '06:00',

      end_time:

    object[
        EVENT_FIELDS.END_TIME
    ] || '18:00'

    })

  )
}
